lista_de_setores = {
    "CMN" : "Câmara Municipal",
    "CDP" : "COMDEP", 
    "GGM" : "Controladoria Geral do Município",
    "ARC" : "Gab. da Prefeitura - Arquivo Central",
    "CLC" : "Gab. da Prefeitura - Compras/Licitação",
    "GAB" : "Gab. da Prefeitura - Gab. do(a) Prefeito(a)",
    "IMP" : "Gab. da Prefeitura - Imprensa",
    "OUV" : "Gab. da Prefeitura - Ouvidoria",
    "JML" : "Gab. da Prefeitura - Junta Militar",
    "PGM" : "Procuradoria Geral do Município",
    "COZ" : "Sec. de Administração - Cozinha",
    "DEP" : "Sec. de Administração - Dep. Pessoal",
    "PTR" : "Sec. de Administração - Patrimônio",
    "PTL" : "Sec. de Administração - Protocolo",
    "RCP" : "Sec. de Administração - Recepção",
    "STR" : "Sec. de Administração - Segurança do Trabalho",
    "TLF" : "Sec. de Administração - Telefonista",
    "AGR" : "Sec. de Agricultura",
    "ASS" : "Sec. de Ass. Social",
    "ABR" : "Sec. de Ass. Social - Abrigo",
    "AIC" : "Sec. de Ass. Social - AICA",
    "CEA" : "Sec. de Ass. Social - CEAM",
    "CEP": "Sec. de Ass. Social - CEPOMP",
    "COM": "Sec. de Ass. Social - COMAD",
    "CST" : "Sec. de Ass. Social - Conselho Tutelar",
    "CRP" : "Sec. de Ass. Social - CRAMP",
    "CRC" : "Sec. de Ass. Social - CRAS - Centro",
    "CRG" : "Sec. de Ass. Social - CRAS - Guarajuba",
    "CRL" : "Sec. de Ass. Social - CRAS - Lages",
    "CRE" : "Sec. de Ass. Social - CREAS",
    "DMU" : "Sec. de Ass. Social - Delegacia da Mulher",
    "CTU" : "Sec. de Cultura e Turismo",
    "DEC" : "Sec. de Des. Econômico",
    "SEM" : "Sec. de Des. Econômico - Sala do Empreendedor",
    "JUC" : "Sec. de Des. Econômico - JUCERJA",
    "EDU" : "Sec. de Educação",
    "EBZ" : "Sec. de Educação - CIEP Brizolão 385 Pr. Augustinho V. de Souza",
    "ECM" : "Sec. de Educação - Creche Mun. Vila São José",
    "EAK" : "Sec. de Educação - E. M. Alan Kardec",
    "BES" : "Sec. de Educação - E. M. Boa Esperança",
    "EAC": "Sec. de Educação - E. M. Com. Azeredo Coutinho",
    "EFL" : "Sec. de Educação - E. M. da Floresta",
    "ETO" : "Sec. de Educação - E. M. Dariele C. T. de Oliveira",
    "EAA" : "Sec. de Educação - E. M. de Ed. Especial Profª Almiracir S. de Azevedo",
    "EMB" : "Sec. de Educação - E. M. de Mário Bello",
    "EDC" : "Sec. de Educação - E. M. Dias da Costa",
    "ECN" : "Sec. de Educação - E. M. Dr. Carlos Nabuco",
    "ERS" : "Sec. de Educação - E. M. Gov. Roberto Silveira",
    "EHP" : "Sec. de Educação - E. M. Hortência Phirro do Vale",
    "EMA" : "Sec. de Educação - E. M. Margarida Alves",
    "EPC" : "Sec. de Educação - E. M. Ponte Coberta",
    "EHF" : "Sec. de Educação - E. M. Pref. Hélio Ferreira da Silva",
    "ENS" : "Sec. de Educação - E. M. Pref. Nicola Salzano",
    "EOT" : "Sec. de Educação - E. M. Profª. Odete Teixeira da Silva",
    "ESA" : "Sec. de Educação - E. M. Santo Antônio",
    "ESJ" : "Sec. de Educação - E. M. São José",
    "ETE" : "Sec. de Educação - E. M. Terra de Educar",
    "CNT" : "Sec. de Finanças - Contabilidade",
    "TSR" : "Sec. de Finanças - Tesouraria",
    "ARR" : "Sec. de Finanças - IPTU - Arrecadação",
    "CAD" : "Sec. de Finanças - IPTU - Cadastro",
    "DAT" : "Sec. de Finanças - IPTU - Dívida Ativa",
    "FIS" : "Sec. de Finanças - IPTU - Fiscalização",
    "GOV" : "Sec. de Governo",
    "CPD" : "Sec. de Governo - CPDM",
    "MAB" : "Sec. de Meio Ambiente",
    "OBR" : "Sec. de Obras",
    "PNJ" : "Sec. de Planejamento",
    "REI" : "Sec. de Rel. Institucionais - SERIN",
    "SAU" : "Sec. de Saúde",
    "SAL" : "Sec. de Saúde - Almoxarifado",
    "SAS" : "Sec. de Saúde - Arquivo da Saúde",
    "SBF" : "Sec. de Saúde - Bolsa Família",
    "SCA" : "Sec. de Saúde - CAPS AD",
    "SCV" : "Sec. de Saúde - CAPS Vila Esperança",
    "SCI" : "Sec. de Saúde - CAPSI",
    "SCZ" : "Sec. de Saúde - Centro de Controle de Zoonose",
    "SCS" : "Sec. de Saúde - Conselho Mun. de Saúde",
    "SCV" : "Sec. de Saúde - Cont. de Vetores - Vig. Amb. em Saúde",
    "SCT" : "Sec. de Saúde - Controladoria",
    "SAT" : "Sec. de Saúde - Coord. de ATAN",
    "SAB" : "Sec. de Saúde - Coord. de Atenção Básica",
    "SHP" : "Sec. de Saúde - Coord. de Hiperdia",
    "SOD" : "Sec. de Saúde - Coord. de Odontologia",
    "SRE" : "Sec. de Saúde - Coord. de Reabilitação",
    "SSF" : "Sec. de Saúde - Coord. de Saúde da Família",
    "SSM" : "Sec. de Saúde - Coord. de Saúde da Mulher",
    "SME" : "Sec. de Saúde - Coord. de Saúde Mental",
    "SLC" : "Sec. de Saúde - Comissão Perm. de Licitação SMS",
    "SFC" : "Sec. de Saúde - Farmácia Básica - Central",
    "SFJ" : "Sec. de Saúde - Farmácia Judicial",
    "SFT" : "Sec. de Saúde - Faturamento", 
    "SGB" : "Sec. de Saúde - Gabinete SEMUS",
    "HLG" : "Sec. de Saúde - Hospital de Lages",
    "HLA" : "Sec. de Saúde - Hospital de Lages - Administração",
    "HCI" : "Sec. de Saúde - Hospital de Lages - Centro de Imagens",
    "HFR" : "Sec. de Saúde - Hospital de Lages - Farmácia",
    "HLB" : "Sec. de Saúde - Hospital de Lages - Laboratório",
    "HOU" : "Sec. de Saúde - Hospital de Lages - Ouvidoria",
    "HSU" : "Sec. de Saúde - Hospital de Lages - Supervisão",
    "SLM" : "Sec. de Saúde - Laboratório Municipal",
    "SOS" : "Sec. de Saúde - Ouvidoria da Saúde",
    "PAM" : "Sec. de Saúde - Posto Amapá",
    "PBN" : "Sec. de Saúde - Posto BNH 1º de Maio",
    "PBJ" : "Sec. de Saúde - Posto Bom Jardim",
    "PCA" : "Sec. de Saúde - Posto Cabral",
    "PCS" : "Sec. de Saúde - Posto Cascata",
    "PLC" : "Sec. de Saúde - Posto Policlínica",
    "PCH" : "Sec. de Saúde - Posto Chacrinha",
    "PGJ" : "Sec. de Saúde - Posto Guarajuba",
    "PJN" : "Sec. de Saúde - Posto Jardim Nova Era",
    "PKM" : "Sec. de Saúde - Posto Km 09", 
    "PLE" : "Sec. de Saúde - Posto Leão XIII",
    "PMU" : "Sec. de Saúde - Posto Multirão",
    "PPA" : "Sec. de Saúde - Posto Pacheco",
    "PPC" : "Sec. de Saúde - Posto Ponte Coberta",
    "PSA" : "Sec. de Saúde - Posto Sabugo",
    "PSJ" : "Sec. de Saúde - Posto São José",
    "PSD" : "Sec. de Saúde - Posto Saudoso",
    "SPT" : "Sec. de Saúde - Protocolo",
    "SRE" : "Sec. de Saúde - Recepção",
    "SRG" : "Sec. de Saúde - Regulação de Exames (SENAC)",
    "SRT" : "Sec. de Saúde - Residência Terapêutica",
    "STC" : "Sec. de Saúde - Residência Terapêutica (10 casinhas)",
    "SRH" : "Sec. de Saúde - RH da Saúde",
    "SAM" : "Sec. de Saúde - SAMU 192 II Paracambi",
    "STP" : "Sec. de Saúde - Transparência",
    "STR" : "Sec. de Saúde - Transporte",
    "SVE" : "Sec. de Saúde - Vigilância Epidemiologia",
    "SVS" : "Sec. de Saúde - Vigilância Sanitária",
    "TID" : "Sec. da Terceira Idade",
    "TRN" : "Sec. de Trab e Renda",
    "TRP" : "Sec. de Transporte",
    "TJA" : "Sec. de Transporte - JARI",
    "DCV" : "Sup. da Defesa Civil",
    "GMP" : "Sup. da Guarda Municipal"
}

equpamentos = {
    "I" : "Impressora",
    "M" : "Monitor",
    "G" : "Gabinete",
    "E" : "Estabilizador",
    "S" : "Scanner",
    "T" : "Telefone"
}

pool_de_equipamentos = {
    "Impressora" : [],
    "Monitor" : [],
    "Gabinete": [],
    "Estabilizador" : [],
    "Scanner" : [],
    "Telefone" : []
}

pool_de_equipamentos["Impressora"].append(2)

n = print(f"{1:04d}")